server:
  port: 9527
spring:
  application:
    name: product-service
datasource:
    username: root
    password: moon1229
    hikari:
      url: jdbc:mysql:///maiqu?useUnicode=true&characterEncoding=utf-8
      driver-class-name: com.mysql.jdbc.Driver
