
server:
  port: 1299
spring:
  application:
    name: zuul-server
zuul:
  ignoredServices: '*'
  routes:
    plat:
      path: /plat/** #平台服务的请求路径
      serviceId: plat-service
  prefix: /services #请求前缀
