server:
  port: 9527
spring:
  application:
    name: product-service
datasource:
    username: root
    password: moon1229
    hikari:
      url: jdbc:mysql://localhost:3306/maiqu?useUnicode=true&characterEncoding=utf8 
      driver-class-name: com.mysql.jdbc.Driver
